export const greetings = {
  morning: [
    "How was your sleep?",
    "Feeling ready today?",
    "What's our vibe this morning?",
    "Ready?",
    "Ready to eat your breakfast?",
    "Eaten your breakfast?",
    "How are we feeling?",
  ],
  afternoon: [
    "How's your day going?",
    "Has the day treated you well?",
    "How are things?",
    "Are you holding up?",
    "You being productive?",
    "How's the afternoon?",
    "Did you have your lunch?",
    "Checking in— you alright?",
    "The day's almost over!",
  ],
  evening: [
    "How was your day?",
    "Was today fun?",
    "Wind down and rest, alright?",
    "The only thing for you now is a good night's sleep!",
    "How are you feeling?",
    "Have you eaten dinner?",
    "The day's almost over!",
  ],
  journal: [
    "Let's Talk About Your Day",
    "The Daily Vibe Report",
    "Unpack That Feeling",
    "Day Break Down",
    "Your Safe Space To Vent",
    "Spill The Beans!",
    "Grab Some Popcorn Because It's About To Be Comical",
    "Are You Not Depressed Yet?",
    "Did You Manage To Uppercut Your Problems?",
    "Your Personal Paper Wall",
  ],
};
